// ============================================================
// PLAN CONFIGURATION CONSTANTS
// ============================================================

/**
 * Default plan configuration
 */
export const PLAN_CONFIG = {
  DEFAULT_WEEKS: 4,
  DAYS_PER_WEEK: 7,
  MIN_WEEKS: 1,
  MAX_WEEKS: 12,
};

/**
 * Day indices (0-based, Monday = 0)
 */
export const DAY_INDICES = {
  MONDAY: 0,
  TUESDAY: 1,
  WEDNESDAY: 2,
  THURSDAY: 3,
  FRIDAY: 4,
  SATURDAY: 5,
  SUNDAY: 6,
};

/**
 * Day names in Spanish
 */
export const DAY_NAMES = [
  "Lunes",
  "Martes",
  "Miércoles",
  "Jueves",
  "Viernes",
  "Sábado",
  "Domingo",
];

/**
 * Training schedule configuration
 */
export const TRAINING_SCHEDULE = {
  GYM_DAYS: [DAY_INDICES.MONDAY, DAY_INDICES.WEDNESDAY],
  QUALITY_DAYS: [DAY_INDICES.TUESDAY, DAY_INDICES.THURSDAY],
  LONG_RUN_DAY: DAY_INDICES.SATURDAY,
  REST_DAYS: [DAY_INDICES.FRIDAY, DAY_INDICES.SUNDAY],
};

// ============================================================
// SESSION AND TRAINING TYPES
// ============================================================

export const SESSION_TYPES = {
  DRO: {
    code: "DRO",
    name: "Desarrollo",
    description: "Sesiones principales de carga",
  },
  COM: {
    code: "COM",
    name: "Compensación",
    description: "Recuperación activa, trabajo suave",
  },
  REC: {
    code: "REC",
    name: "Recuperación",
    description: "Sesiones muy ligeras",
  },
  DES: { code: "DES", name: "Descanso", description: "Sin actividad" },
  CPT: {
    code: "CPT",
    name: "Competencia",
    description: "Día de carrera oficial",
  },
  EVA: {
    code: "EVA",
    name: "Evaluación",
    description: "Test o prueba de rendimiento",
  },
  MAN: {
    code: "MAN",
    name: "Mantenimiento",
    description: "Sostener nivel actual",
  },
};

export const TRAINING_TYPES = {
  SER: { code: "SER", name: "Series" },
  FTK: { code: "FTK", name: "Fartlek" },
  CCN: { code: "CCN", name: "Carrera continua" },
  CUE: { code: "CUE", name: "Cuestas" },
  VEL: { code: "VEL", name: "Velocidad" },
  CRJ: { code: "CRJ", name: "Contra reloj" },
  TRO: { code: "TRO", name: "Trote" },
  ACE: { code: "ACE", name: "Aceleraciones" },
  PRO: { code: "PRO", name: "Progresivo" },
};

// Define which training types can be combined (first type -> array of compatible second types)
export const TRAINING_COMPATIBILITY = {
  SER: ["CRJ", "VEL", "FTK"],
  FTK: ["SER", "CCN"],
  CRJ: ["SER", "FTK"],
  VEL: ["SER", "ACE"],
  CUE: ["VEL", "SER"],
  CCN: ["FTK", "PRO"],
  TRO: ["CCN"],
  ACE: ["VEL"],
  PRO: ["CCN"],
};

export const SYMBOLS = {
  WARMUP: "[C]",
  COOLDOWN: "[A]",
  SEPARATOR: "||",
  BULLET: "•",
  REST_SERIES: "D:",
  REST_BLOCK: "DB:",
  UP: "↑",
  DOWN: "↓",
  CLIMB: "↗",
  DESCENT: "↘",
  PROGRESSION: "⇢",
  PROGRESSION_DOWN: "↘",
  TRANSITION: "→",
  STRONG: "F.",
  SOFT: "S.",
  PACE: "R/",
  AVG: "x̄",
  CHANGE: "Δ",
  BEST_PACE: "MRP",
  APPROX: "≈",
  SPRINT: "SP",
  CIRCUIT: "G",
  REST_30_SEC: '(30")',
};

export const GYM_EXERCISES = {
  LOWER: [
    "ABDUCTORES CON BANDA ELÁSTICA",
    "ABDUCTORES EN MÁQUINA",
    "ABDUCTORES EN POLEA",
    "ABDUCCIÓN DE CADERA",
    "ADUCTORES COPENHAGUE",
    "ADUCTORES EN MÁQUINA",
    "ADUCTORES EN POLEA",
    "ADUCCIÓN DE CADERA",
    "BOX JUMPS",
    "BOX SQUAT",
    "BUENOS DÍAS CON BANDA",
    "BUENOS DÍAS CON BARRA",
    "BUENOS DÍAS SENTADO",
    "BUG BÚLGARO",
    "BURPEES",
    "BURPEES CON PECHADA",
    "BURPEES CON SALTO AL CAJÓN",
    "CURL FEMORAL ACOSTADO",
    "CURL FEMORAL CON MANCUERNA",
    "CURL FEMORAL DE PIE",
    "CURL FEMORAL SENTADO",
    "CURL NÓRDICO",
    "DESPLANTES CAMINANDO",
    "DESPLANTES CRUZADOS (CURTSY)",
    "DESPLANTES ESTÁTICOS",
    "DESPLANTES HACIA ATRÁS",
    "DESPLANTES LATERALES",
    "ELEVACIÓN DE GEMELOS SENTADO",
    "ELEVACIÓN DE PELVIS",
    "ELEVACIÓN DE PELVIS A UNA PIERNA",
    "ELEVACIÓN DE TALONES",
    "ELEVACIÓN DE TALONES CON MANCUERNA",
    "ELEVACIÓN DE TALONES EN PRENSA",
    "ELEVACIÓN DE TALONES TIPO BURRO",
    "ESTOCADA CAMINANDO",
    "ESTOCADA INVERSA",
    "ESTOCADA LATERAL",
    "ESTOCADAS ALTERNAS",
    "EXTENSIÓN CUÁDRICEPS",
    "EXTENSIÓN CUÁDRICEPS UNILATERAL",
    "GLUTE BRIDGE",
    "GLUTE BRIDGE CON BARRA",
    "GLUTE HAM RAISE",
    "GOBLET SQUAT",
    "HACK SQUAT CON BARRA",
    "HACK SQUAT EN MÁQUINA",
    "HACK SQUAT INVERSO",
    "HIP THRUST",
    "HIP THRUST A UNA PIERNA",
    "HIP THRUST CON BARRA",
    "HIP THRUST CON MANCUERNA",
    "HIP THRUST EN MÁQUINA",
    "JUMPING LUNGES",
    "JUMPING SQUATS",
    "KANG SQUAT",
    "LEG PRESS 45°",
    "LEG PRESS HORIZONTAL",
    "LEG PRESS POSICIÓN ALTA",
    "LEG PRESS POSICIÓN BAJA",
    "LEG PRESS UNILATERAL",
    "PATADA DE GLÚTEO",
    "PATADA DE GLÚTEO EN CUADRUPEDIA",
    "PATADA DE GLÚTEO EN MÁQUINA",
    "PATADA DE GLÚTEO EN POLEA",
    "PESO MUERTO",
    "PESO MUERTO A UNA PIERNA",
    "PESO MUERTO ALTO",
    "PESO MUERTO CON BARRA HEXAGONAL",
    "PESO MUERTO DEFICIT",
    "PESO MUERTO PIERNAS RÍGIDAS",
    "PESO MUERTO RUMANO",
    "PESO MUERTO RUMANO CON MANCUERNAS",
    "PESO MUERTO RUMANO UNILATERAL",
    "PESO MUERTO SUMO",
    "PISTOL SQUAT",
    "PISTOL SQUAT ASISTIDA",
    "PRENSA 45°",
    "PRENSA INCLINADA",
    "RACK PULLS",
    "SENTADILLA ANDERSON",
    "SENTADILLA BARRA TRASERA HIGH BAR",
    "SENTADILLA BARRA TRASERA LOW BAR",
    "SENTADILLA BÚLGARA",
    "SENTADILLA BÚLGARA CON BARRA",
    "SENTADILLA BÚLGARA CON MANCUERNAS",
    "SENTADILLA COMPLETA (MNC)",
    "SENTADILLA CON SALTO",
    "SENTADILLA FRONTAL",
    "SENTADILLA FRONTAL AGARRE CRUZADO",
    "SENTADILLA FRONTAL AGARRE OLÍMPICO",
    "SENTADILLA GOBLET",
    "SENTADILLA HACK",
    "SENTADILLA ISOMÉTRICA (WALL SIT)",
    "SENTADILLA JEFFERSON",
    "SENTADILLA OVERHEAD",
    "SENTADILLA SISSY",
    "SENTADILLA SUMO",
    "SENTADILLA ZERCHER",
    "STEP UP",
    "STEP UP CON BARRA",
    "STEP UP CON MANCUERNAS",
    "STEP UP LATERAL",
    "ZANCADAS",
    "ZANCADAS CON MANCUERNAS",
  ],
  UPPER_PUSH: [
    "APERTURAS CON MANCUERNAS BANCO DECLINADO",
    "APERTURAS CON MANCUERNAS BANCO INCLINADO",
    "APERTURAS CON MANCUERNAS BANCO PLANO",
    "APERTURAS EN MÁQUINA (PECK DECK)",
    "APERTURAS EN POLEA",
    "ARNOLD PRESS DE PIE",
    "ARNOLD PRESS SENTADO",
    "AROUND THE WORLD",
    "BANCO DECLINADO CON BARRA",
    "BANCO DECLINADO CON MANCUERNAS",
    "BANCO INCLINADO CON BARRA",
    "BANCO INCLINADO CON MANCUERNAS",
    "BANCO INCLINADO EN SMITH",
    "BANCO PLANO AGARRE CERRADO",
    "BANCO PLANO CON BARRA",
    "BANCO PLANO CON MANCUERNAS",
    "BANCO PLANO EN SMITH",
    "CROSSOVER ALTO",
    "CROSSOVER BAJO",
    "CROSSOVER MEDIO",
    "CRUCE DE POLEAS",
    "DIPS (FONDOS) ENTRE BANCOS",
    "DIPS (FONDOS) PECHO",
    "DIPS (FONDOS) TRÍCEPS",
    "DIPS EN BANCO",
    "DIPS EN MÁQUINA ASISTIDA",
    "DIPS EN PARALELAS",
    "ELEVACIÓN FRONTAL CON BARRA",
    "ELEVACIÓN FRONTAL CON DISCO",
    "ELEVACIÓN FRONTAL CON MANCUERNAS",
    "ELEVACIÓN FRONTAL CON POLEA",
    "ELEVACIÓN LATERAL ACOSTADO DE LADO",
    "ELEVACIÓN LATERAL CON MANCUERNAS DE PIE",
    "ELEVACIÓN LATERAL CON MANCUERNAS SENTADO",
    "ELEVACIÓN LATERAL EN MÁQUINA",
    "ELEVACIÓN LATERAL EN POLEA",
    "EXTENSIÓN DE TRÍCEPS AGARRE INVERSO",
    "EXTENSIÓN DE TRÍCEPS CON BARRA V",
    "EXTENSIÓN DE TRÍCEPS CON CUERDA",
    "EXTENSIÓN DE TRÍCEPS EN POLEA",
    "EXTENSIÓN DE TRÍCEPS UNILATERAL",
    "FLOOR PRESS",
    "FLOOR PRESS CON MANCUERNAS",
    "FONDOS",
    "FONDOS EN BANCO",
    "FRENCH PRESS CON BARRA Z",
    "FRENCH PRESS CON MANCUERNAS",
    "GUILLOTINE PRESS",
    "HALO CON DISCO",
    "HALO CON KETTLEBELL",
    "HANDSTAND PUSHUPS",
    "KICKBACKS CON MANCUERNA",
    "KICKBACKS EN POLEA",
    "LAGARTIJAS",
    "LAGARTIJAS ABIERTAS",
    "LAGARTIJAS ARCHER",
    "LAGARTIJAS CON PALMADA",
    "LAGARTIJAS DECLINADAS",
    "LAGARTIJAS DIAMANTE",
    "LAGARTIJAS INCLINADAS",
    "LANDMINE PRESS",
    "LANDMINE PRESS A DOS MANOS",
    "LU RAISES",
    "MÁQUINA DE HOMBROS",
    "MÁQUINA DE PECHO",
    "MEDIALUNAS",
    "MILITARY PRESS DE PIE",
    "MILITARY PRESS SENTADO",
    "PRESS ARNOLD",
    "PRESS BANCA",
    "PRESS BANCA DECLINADO",
    "PRESS BANCA INCLINADO",
    "PRESS CON MANCUERNAS",
    "PRESS DE HOMBRO CON BARRA",
    "PRESS DE HOMBRO CON MANCUERNAS",
    "PRESS FRANCÉS",
    "PRESS GUILLOTINA",
    "PRESS LANDMINE",
    "PRESS MILITAR",
    "PRESS PARADO",
    "PRESS SVEND",
    "PRESS TATE",
    "PUSH PRESS",
    "REMO AL CUELLO CON BARRA",
    "REMO AL CUELLO CON MANCUERNAS",
    "REMO AL CUELLO CON POLEA",
    "ROMPECRÁNEOS CON BARRA Z",
    "ROMPECRÁNEOS CON MANCUERNAS",
    "THRUSTER CON BARRA",
    "THRUSTER CON MANCUERNAS",
    "TRÍCEPS EN POLEA",
    "TRÍCEPS TUMBADO",
    "VUELOS LATERALES",
    "VUELOS POSTERIORES",
    "Z-PRESS",
  ],
  UPPER_PULL: [
    "ANTEBRAZO CON BARRA PRONACIÓN",
    "ANTEBRAZO CON BARRA SUPINACIÓN",
    "ANTEBRAZO CON MANCUERNA",
    "ANTEBRAZO RODILLO",
    "APERTURAS INVERSAS CON MANCUERNAS",
    "APERTURAS INVERSAS EN MÁQUINA",
    "APERTURAS INVERSAS EN POLEA",
    "BAND PULL-APARTS",
    "CHIN UPS",
    "CROSS-BODY HAMMER CURL",
    "CURL ARAÑA",
    "CURL CON BARRA",
    "CURL CON BARRA Z",
    "CURL CON MANCUERNAS ALTERNO",
    "CURL CON MANCUERNAS SIMULTÁNEO",
    "CURL CONCENTRADO",
    "CURL DE BÍCEPS",
    "CURL DE MUÑECA",
    "CURL EN BANCO INCLINADO",
    "CURL EN POLEA",
    "CURL MARTILLO",
    "CURL MARTILLO CON SOGA",
    "CURL PREDICADOR BARRA Z",
    "CURL PREDICADOR EN MÁQUINA",
    "CURL PREDICADOR MANCUERNA",
    "CURL ZOTTMAN",
    "DOMINADAS",
    "DOMINADAS AGARRE NEUTRO",
    "DOMINADAS ASISTIDAS",
    "DOMINADAS CERRADAS",
    "DOMINADAS CON LASTRE",
    "DOMINADAS ESCAPULARES",
    "DOMINADAS SUPINAS",
    "DRAG CURL",
    "ENCOGIMIENTOS CON BARRA",
    "ENCOGIMIENTOS CON MANCUERNAS",
    "ENCOGIMIENTOS EN SMITH",
    "FACE PULL",
    "FACE PULL SENTADO",
    "HIGH PULL",
    "JALÓN AL PECHO AGARRE ABIERTO",
    "JALÓN AL PECHO AGARRE CERRADO",
    "JALÓN AL PECHO AGARRE NEUTRO",
    "JALÓN AL PECHO UNILATERAL",
    "JALÓN CON BRAZOS RECTOS",
    "JALÓN TRAS NUCA",
    "LANDMINE ROW",
    "MEADOWS ROW",
    "MUSCLE UP EN ANILLAS",
    "MUSCLE UP EN BARRA",
    "PÁJAROS CON MANCUERNAS",
    "PENDLAY ROW",
    "PULL OVER",
    "PULL OVER CON BARRA",
    "PULL OVER CON MANCUERNA",
    "PULL OVER EN POLEA",
    "PULL-THROUGH",
    "REMO A UNA MANO",
    "REMO CON BARRA",
    "REMO CON BARRA AGARRE SUPINO",
    "REMO CON MANCUERNA",
    "REMO CON MANCUERNAS A DOS MANOS",
    "REMO EN BARRA T CON APOYO",
    "REMO EN BARRA T LIBRE",
    "REMO EN MÁQUINA",
    "REMO EN POLEA BAJA",
    "REMO EN POLEA BAJA AGARRE ANCHO",
    "REMO INVERTIDO",
    "REMO PENDLAY",
    "REMO T-BAR",
    "RENEGADE ROW",
    "REVERSE CURL",
    "SEAL ROW",
    "SHRUGS CON BARRA",
    "SHRUGS CON MANCUERNAS",
    "Y-RAISE",
  ],
  CORE: [
    "AB WHEEL",
    "ARCOIRIS (RAINBOWS)",
    "BALL SLAMS",
    "BEAR CRAWL",
    "BIRD DOG",
    "CRUNCH ABDOMINAL",
    "CRUNCH EN MÁQUINA",
    "CRUNCH EN POLEA ALTA",
    "CRUNCH INVERSO",
    "CRUNCH OBLICUO",
    "DEAD BUG",
    "DRAGON FLAG",
    "ELEVACIÓN DE PIERNAS",
    "ELEVACIÓN DE PIERNAS COLGADO",
    "ELEVACIÓN DE PIERNAS EN SILLA ROMANA",
    "ELEVACIÓN DE RODILLAS COLGADO",
    "ESCALADORES (MOUNTAIN CLIMBERS)",
    "EXTENSIONES LUMBARES EN BANCO ROMANO",
    "EXTENSIONES LUMBARES EN MÁQUINA",
    "FLUTTER KICKS",
    "GIROS RUSOS CON BALÓN",
    "GIROS RUSOS CON DISCO",
    "HIPEREXTENSIÓN 45°",
    "HIPEREXTENSIÓN HORIZONTAL",
    "HOLLOW BODY HOLD",
    "JEFFERSON CURL",
    "L-SIT",
    "LANDMINE TWIST",
    "LEVANTAMIENTO TURCO",
    "MOUNTAIN CLIMBERS",
    "PALLOF PRESS",
    "PALLOF PRESS CON ROTACIÓN",
    "PLANCHA CON ELEVACIÓN DE BRAZO",
    "PLANCHA CON ELEVACIÓN DE PIERNA",
    "PLANCHA FRONTAL",
    "PLANCHA LATERAL",
    "PLANCHA SOBRE FITBALL",
    "REVERSE HYPER",
    "RODILLAS AL PECHO",
    "RODILLO ABDOMINAL",
    "RUSSIAN TWIST",
    "SCISSORS",
    "SIDE BENDS",
    "SIT UPS",
    "SUPERMAN",
    "TOES TO BAR",
    "TWIST CON POLEA",
    "V-UPS",
    "VACÍO ABDOMINAL",
    "WINDMILL CON KETTLEBELL",
    "WINDSHIELD WIPERS",
    "WOOD CHOPPER ABAJO-ARRIBA",
    "WOOD CHOPPER ARRIBA-ABAJO",
    "WOOD CHOPPER HORIZONTAL",
  ],
};

export const ALL_GYM_EXERCISES = [
  ...GYM_EXERCISES.LOWER,
  ...GYM_EXERCISES.UPPER_PUSH,
  ...GYM_EXERCISES.UPPER_PULL,
  ...GYM_EXERCISES.CORE,
].sort();

// Metadata enriquecida (opcional) para ejercicios del SISTEMA, keyeada por el
// nombre exacto tal como aparece en GYM_EXERCISES. No es obligatorio que un
// ejercicio tenga entrada aquí — si no la tiene, la UI simplemente lo muestra
// como nombre plano (comportamiento original, sin romper nada existente).
// Se agregan solo algunos ejemplos reales por categoría; el resto se puede
// enriquecer desde el panel Admin > Ejercicios (mismo shape, persistido en
// crm_custom_exercise_meta) sin tocar este archivo.
export const EXERCISE_METADATA: Record<
  string,
  {
    exerciseId?: string;
    gifUrl?: string;
    targetMuscles?: string[];
    bodyParts?: string[];
    equipments?: string[];
    secondaryMuscles?: string[];
    instructions?: string[];
  }
> = {
  "BANCO PLANO CON BARRA": {
    exerciseId: "EIeI8Vf",
    gifUrl: "https://static.exercisedb.dev/media/EIeI8Vf.gif",
    targetMuscles: ["pectorals"],
    bodyParts: ["chest"],
    equipments: ["barbell"],
    secondaryMuscles: ["triceps", "shoulders"],
    instructions: [
      "Paso 1: Acuéstate boca arriba en el banco con los pies apoyados en el suelo.",
      "Paso 2: Sujeta la barra con agarre pronado, un poco más ancho que los hombros.",
      "Paso 3: Levanta la barra del rack y colócala sobre el pecho con los brazos extendidos.",
      "Paso 4: Baja la barra lentamente hasta que toque el pecho.",
      "Paso 5: Haz una breve pausa al tocar el pecho.",
      "Paso 6: Empuja la barra de vuelta a la posición inicial.",
      "Paso 7: Repite el número de repeticiones deseado.",
    ],
  },
  "SENTADILLA COMPLETA (MNC)": {
    targetMuscles: ["quadriceps"],
    bodyParts: ["upper legs"],
    equipments: ["barbell"],
    secondaryMuscles: ["glutes", "hamstrings", "calves"],
    instructions: [
      "Paso 1: Coloca la barra sobre los trapecios, pies al ancho de hombros.",
      "Paso 2: Baja las caderas flexionando rodillas y cadera manteniendo la espalda neutra.",
      "Paso 3: Desciende hasta que los muslos queden paralelos al suelo o más abajo.",
      "Paso 4: Empuja el suelo con los pies para volver a la posición inicial.",
    ],
  },
  DOMINADAS: {
    targetMuscles: ["lats"],
    bodyParts: ["back"],
    equipments: ["body weight"],
    secondaryMuscles: ["biceps", "forearms"],
    instructions: [
      "Paso 1: Cuelga de la barra con agarre pronado, manos al ancho de hombros.",
      "Paso 2: Tira de tu cuerpo hacia arriba hasta que la barbilla supere la barra.",
      "Paso 3: Baja controladamente hasta la extensión completa de brazos.",
    ],
  },
  "PLANCHA FRONTAL": {
    targetMuscles: ["abs"],
    bodyParts: ["waist"],
    equipments: ["body weight"],
    secondaryMuscles: ["shoulders", "glutes"],
    instructions: [
      "Paso 1: Apóyate sobre antebrazos y puntas de pies, cuerpo en línea recta.",
      "Paso 2: Contrae el abdomen y los glúteos, evitando que la cadera caiga.",
      "Paso 3: Mantén la posición el tiempo indicado respirando de forma constante.",
    ],
  },
};

export const GYM_PROGRESSION = {
  // Placeholder if needed, or remove import in GymSessionEditor if not used
  DEFAULT: "Linear",
};
